version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerized-laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./.docker/php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dockerized-laravel-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: dockerized-laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    volumes:
      - dockerized-laravel-data:/var/lib/mysql
    networks:
      - dockerized-laravel-network
    ports:
      - "3306:3306"

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: dockerized-laravel-webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      # Use a single file mount instead of a directory
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dockerized-laravel-network
    depends_on:
      - app

  # Redis for Cache and Queue
  redis:
    image: redis:alpine
    container_name: dockerized-laravel-redis
    restart: unless-stopped
    networks:
      - dockerized-laravel-network
    ports:
      - "6379:6379"

# Networks
networks:
  dockerized-laravel-network:
    driver: bridge

# Volumes
volumes:
  dockerized-laravel-data:
    driver: local