version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: svelte
      POSTGRES_PASSWORD: svelte
      POSTGRES_DB: svelte
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
